spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    hikari:
      username: "{cipher}AQAsyLrEuMWbNIaZ1iCVeT3Y+su7FACCHWPo+ATA0AqzUdEX5nWs/vCLrzsj52hO1hSciIOYZl4eMFwfUdLgpsQv2UwIcXv/GQlujFMdolElXfr5Yc6RehXJtrpnQPaqhOH/R4mipDpLbTyoSue4nMu6iruKSXE2hZ89QCnK5InTCqEhGgorcqqcvzjQiILYhWwA4Ndx8HYuUbYd37sKmd1lMBJ+Y7JGLB3sIup8aNVYfkh65VXvSAXy48vjdakFPC2k1ks6MoL1vXcB6WvfZu7ZhYtxDDjfrqXCAkq2kLrt0JRVRUuRAu6ABu7/gwfRM7Zx4b2wI+9HInYww2hEFnU7rRzOWTOVk1auRaSF0abx1LsWlBiVNIHZGJiZFUUSgUY="
      password:

token:
  expiration_time: 864000000
  secret: "{cipher}AQAgK+3xVQUjDGVzevbMIJM6xLgG3an1fClc6JJVtNEPgP8CkQ4nPtr/jT3IaeCybNFQnl5uWTXMbHvLxPVBLbeAjT+5ZN7m9qR9kWmWAm2j9X1JrtouiXbEhjvs97WAs0rpdF8KQ3brEp26iB9kjzTvTAo0DOfXuDcy/K0YgIlnWRr8/GnVMLNhV+0/NlPWWIB0uKBpwplFEcyGu6zw+ulsUl5KU3DDqbtK9WnA+fNB1iqn8IF4koBKE+wb17fmUiEgrL/7KuuvaZ5PkmtWRekSN/wYNcRBZEKRD3GLmHjOsLGmT+U7IqQNpQoeBL8QGcC9+gFx2xjnNt283hk5/gDktY3yUaQNSmOTjQyod6fnySNLlUzqXNGa/dLMG+v4Ec3Bczkyfg17kMhxgd6JFMop6xo9glCNAVd1yGP31rLWeku9vb2MFZl7CQ+J1b6AGwYiAid5xlrAOaa1V9QuzZwPq6i4U+Z7Hlfsxql/vvqTuU1GfTpqBguiHHinw/wsE6mZVkH4zr9P2rg6XRtJ6qL2N/ZcOPKVb8AUotKnRKVpxQ=="

gateway:
  ip: 192.168.0.25

order_service:
  url: http://127.0.0.1:8000/order-service/%s/orders
  lb_url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: User orders is empty.
